import type { Metadata } from 'next';
import './globals.scss';

// Separate import for PrimeReact styles to avoid override issue with globals stylesheet
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/soho-light/theme.css';

export const metadata: Metadata = {
  title: 'Shows Next App',
  description: 'Not generated by AI',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
